#!/usr/bin/env python3
"""Build the WordPress plugin from the standalone tool.

Copies ../index.html into miter-and-mat/app/index.html as a full HTML
document that loads its fonts and JSZip from the plugin instead of from
Google Fonts and cdnjs, then zips the plugin for upload.

    python3 MiterAndMat/wordpress/build.py
"""
import pathlib
import re
import zipfile

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "index.html"
PLUGIN = HERE / "miter-and-mat"
OUT = PLUGIN / "app" / "index.html"
ZIP = HERE / "miter-and-mat.zip"

html = SRC.read_text(encoding="utf-8")

fonts = re.compile(r'<link rel="preconnect"[^>]*>\n<link rel="preconnect"[^>]*>\n<link rel="stylesheet" href="https://fonts\.googleapis\.com[^>]*>\n')
assert fonts.search(html), "Google Fonts links not found"
html = fonts.sub('<meta name="robots" content="noindex">\n<link rel="stylesheet" href="fonts/fonts.css">\n', html)

jszip = '<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>'
assert jszip in html, "JSZip script tag not found"
html = html.replace(jszip, '<script src="jszip.min.js"></script>')

# The artifact source is a body fragment; the plugin serves a full document.
head, sep, body = html.partition('<div class="app">')
assert sep, "app container not found"
html = (
    "<!doctype html>\n<!-- Generated by wordpress/build.py from MiterAndMat/index.html. Edit that file, not this one. -->\n"
    '<html lang="en">\n<head>\n' + head + "</head>\n<body>\n" + sep + body + "</body>\n</html>\n"
)
assert "googleapis" not in html and "cdnjs" not in html
OUT.write_text(html, encoding="utf-8")

with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
    for path in sorted(PLUGIN.rglob("*")):
        if path.is_file():
            z.write(path, path.relative_to(HERE))
print(f"wrote {OUT.relative_to(HERE.parent.parent)} and {ZIP.relative_to(HERE.parent.parent)} ({ZIP.stat().st_size // 1024} KB)")
